#!/bin/bash
set -euo pipefail

# pull in additional repo files
## Azure CLI
rpm --import https://packages.microsoft.com/keys/microsoft.asc
echo -e "[azure-cli]
name=Azure CLI
baseurl=https://packages.microsoft.com/yumrepos/azure-cli
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc" | tee /etc/yum.repos.d/azure-cli.repo

## Google SDK
tee -a /etc/yum.repos.d/google-cloud-sdk.repo << EOM
[google-cloud-cli]
name=Google Cloud CLI
baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el8-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=0
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
       https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOM

## VSCode
echo -e "[code]
name=Visual Studio Code
baseurl=https://packages.microsoft.com/yumrepos/vscode
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc" | tee /etc/yum.repos.d/vscode.repo

# install packages
grep -v '^#' deps.txt | xargs dnf install -y
grep -v '^#' builddeps.txt | xargs dnf builddep -y

# cosa
(git clone https://github.com/coreos/coreos-assembler
 cd coreos-assembler
 sed -i "s/frozendeps=.*/frozendeps=/" build.sh
 ./build.sh configure_yum_repos
 ./build.sh install_rpms)

# install oc
(curl -LO https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/latest/openshift-client-linux.tar.gz
 tar -xf openshift-client-linux.tar.gz
 cp oc /usr/local/bin
 rm oc kubectl README.md openshift-client-linux.tar.gz)

# everything in the FCOS buildroot image
(git clone https://github.com/coreos/fedora-coreos-config
 cd fedora-coreos-config
 ci/buildroot/install-buildroot.sh)

# cleanup dnf cache
dnf clean all

# we want the host srv
rmdir /srv && ln -sT /run/host/srv /srv

# install rhsetup
cp rhsetup /usr/bin
