#!/bin/bash
set -euo pipefail

# pull in additional repo files

## RPM Fusion
dnf install -y \
  https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
  https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

## Azure CLI
rpm --import https://packages.microsoft.com/keys/microsoft.asc
echo -e "[azure-cli]
name=Azure CLI
baseurl=https://packages.microsoft.com/yumrepos/azure-cli
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc" | tee /etc/yum.repos.d/azure-cli.repo

## Google SDK
rpm --import https://packages.cloud.google.com/yum/doc/yum-key.gpg
rpm --import https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
tee -a /etc/yum.repos.d/google-cloud-sdk.repo << EOM
[google-cloud-cli]
name=Google Cloud CLI
baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el8-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=0
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
       https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOM

## VSCode
echo -e "[code]
name=Visual Studio Code
baseurl=https://packages.microsoft.com/yumrepos/vscode
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc" | tee /etc/yum.repos.d/vscode.repo

## Terraform
curl -L -o /etc/yum.repos.d/hashicorp.repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo

## lazygit Copr
tee -a /etc/yum.repos.d/lazygit-copr.repo << EOM
[copr:copr.fedorainfracloud.org:dejan:lazygit]
name=Copr repo for lazygit owned by dejan
baseurl=https://download.copr.fedorainfracloud.org/results/dejan/lazygit/fedora-$(rpm -E %fedora)-x86_64/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://download.copr.fedorainfracloud.org/results/dejan/lazygit/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
EOM

# install packages
grep -v '^#' deps.txt | xargs dnf install -y

# install oc
(curl -LO https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/latest/openshift-client-linux.tar.gz
 tar -xf openshift-client-linux.tar.gz
 cp oc /usr/local/bin
 rm oc kubectl README.md openshift-client-linux.tar.gz)

# cleanup dnf cache
dnf clean all

# install yq binary
# https://release-monitoring.org/project/303696/
set -x
yq_release=$(curl -s "https://release-monitoring.org/api/v2/versions/?project_id=303696" | jq -r '.stable_versions[0]')
curl -LO "https://github.com/mikefarah/yq/releases/download/v${yq_release}/yq_linux_amd64.tar.gz"
tar -xzf yq_linux_amd64.tar.gz
cp ./yq_linux_amd64 /usr/local/bin/yq
set +x

# install bpytop
pip3 install bpytop --upgrade

# we want the host srv
rmdir /srv && ln -sT /run/host/srv /srv

# install rhsetup
cp rhsetup /usr/bin

# install host-runner shim
cp host-runner /usr/local/bin/

# setup host-runner aliases
ln -s /usr/local/bin/host-runner /usr/local/bin/podman
ln -s /usr/local/bin/host-runner /usr/local/bin/rpm-ostree

# install heif-convert
pip3 install --upgrade heif-convert
