#!/bin/bash
set -xeuo pipefail

source /etc/os-release

# install rh-pre-commit
cd $(mktemp -d)
git clone https://gitlab.cee.redhat.com/infosec-public/developer-workbench/tools.git
cd tools/rh-pre-commit
python3 -m pip install --upgrade --user pip
make install
