name: Build

env:
  QUAY_BASE: quay.io/miabbott/pet
  TOOLBOX: quay.io/rhel-devel-tools/rhel-developer-toolbox

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: "Build container image"
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.0
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Get podman info
        run: |
          set -xeou pipefail
          podman info
      - name: Build container image
        run: |
          set -xeuo pipefail
          podman build --from $TOOLBOX:latest -t "${{ env.QUAY_BASE }}:latest" .
      - name: Push container image
        run: |
          set -xeuo pipefail
          mkdir -p ~/.docker
          cat > ~/.docker/config.json <<EOF
          ${{ secrets.QUAY_AUTH }}
          EOF
          # disable zstd:chunked until https://github.com/containers/podman/issues/24885 is addressed
          # podman push --compression-format=zstd:chunked "${{ env.QUAY_BASE }}:latest"
          podman push "${{ env.QUAY_BASE }}:latest"
          rm ~/.docker/config.json
      - name: Update README and Containerfile
        run: |
          # This is load-bearing: GitHub will disable the job if the repo
          # doesn't stay active.  Do not enable branch protection for main;
          # it'll break this.
          set -xeuo pipefail
          git config user.name 'Micah Abbott'
          git config user.email miabbott@redhat.com
          sed -i "s/updated-.*-green/updated-$(date +%Y--%m--%d)-green/" README.md
          git add README.md Containerfile
          if git diff --quiet --staged --exit-code; then
            echo "README.md already up to date"
            exit 0
          fi
          git commit -m "README.md: update build date"
          git push
